#!/usr/bin/env bash
# This script:
#   Create a file /var/run/holbertonscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/holbertonscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.

echo "$$" > /var/run/holbertonscript.pid

termfunc() {
    rm /var/run/holbertonscript.pid
    exit
}


while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && termfunc' SIGTERM
    trap 'termfunc' SIGQUIT
done
