#!/usr/bin/env bash
# This script:
#   Create a file /var/run/holbertonscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/holbertonscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.

PRID=$$
echo "$PRID" > /var/run/holbertonscript.pid

function Do_not_love_at_Signal()
{
    echo "Y U no love me?!"
}

function Quit_at_Signal()
{
    echo "I hate the kill command"
    rm -f /var/run/holbertonscript.pid
    kill -9 $PRID
}

trap Do_not_love_at_Signal SIGINT
trap Quit_at_Signal SIGQUIT SIGTERM

while :
do
    echo "To infinity and beyond"
    sleep 2
done
