#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

exec < /etc/passwd

while read -r passwd_output ; do
      echo "$passwd_output" | cut -d':' -f1,3,6
done